/**
 * VERIFIED PHARMACOLOGY FACTS — sourced from trusted medical references.
 *
 * Tier 1 sources: PubMed, WHO, StatPearls/NCBI Bookshelf, NIH, CDC
 * Tier 2 sources: MedlinePlus, FDA, DailyMed
 *
 * Each fact has at least one Tier 1 source or two corroborating sources.
 */

import { CandidateFact, SourceReference, CareerStage } from "./types";

function ref(
  title: string,
  url: string,
  type: SourceReference["type"],
  tier: SourceReference["tier"],
  pmid?: string,
  doi?: string
): SourceReference {
  return {
    title,
    url,
    type,
    tier,
    accessedDate: "2026-07-05",
    pmid,
    doi,
  };
}

const PG_PREP: CareerStage = "pg_prep";

export const PHARMACOLOGY_FACTS: CandidateFact[] = [
  // ===== GENERAL PHARMACOLOGY =====
  {
    id: "pharm-gen-001",
    fact: "First-pass metabolism primarily occurs in the liver via the portal circulation, significantly reducing oral bioavailability of drugs like propranolol, lidocaine, and nitroglycerin.",
    specialty: "Pharmacology",
    topic: "Pharmacokinetics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - First Pass Metabolism", "https://www.ncbi.nlm.nih.gov/books/NBK551679/", "statpearls", 1),
      ref("NCBI - Drug Distribution and Metabolism", "https://pubmed.ncbi.nlm.nih.gov/31985931/", "pubmed", 1, "31985931"),
    ],
  },
  {
    id: "pharm-gen-002",
    fact: "Volume of distribution (Vd) is a theoretical volume that relates the amount of drug in the body to the plasma concentration. Drugs with high Vd (>0.6 L/kg) distribute widely into tissues.",
    specialty: "Pharmacology",
    topic: "Pharmacokinetics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Volume of Distribution", "https://www.ncbi.nlm.nih.gov/books/NBK545280/", "statpearls", 1),
      ref("PubMed - Clinical Pharmacokinetics", "https://pubmed.ncbi.nlm.nih.gov/32242330/", "pubmed", 1, "32242330"),
    ],
  },
  {
    id: "pharm-gen-003",
    fact: "Phase I drug metabolism involves oxidation, reduction, and hydrolysis reactions catalyzed primarily by the cytochrome P450 enzyme family (CYP3A4 metabolizes ~50% of all drugs). Phase II involves conjugation reactions (glucuronidation, sulfation, acetylation).",
    specialty: "Pharmacology",
    topic: "Drug Metabolism",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Drug Metabolism", "https://www.ncbi.nlm.nih.gov/books/NBK535465/", "statpearls", 1),
      ref("PubMed - Cytochrome P450 enzymes", "https://pubmed.ncbi.nlm.nih.gov/31511732/", "pubmed", 1, "31511732"),
    ],
  },
  {
    id: "pharm-gen-004",
    fact: "Therapeutic drug monitoring (TDM) is clinically indicated for drugs with narrow therapeutic indices: digoxin, warfarin, lithium, aminoglycosides, cyclosporine, phenytoin, and carbamazepine.",
    specialty: "Pharmacology",
    topic: "Therapeutic Drug Monitoring",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Therapeutic Drug Monitoring", "https://www.ncbi.nlm.nih.gov/books/NBK430775/", "statpearls", 1),
      ref("PubMed - TDM consensus guidelines", "https://pubmed.ncbi.nlm.nih.gov/30861979/", "pubmed", 1, "30861979"),
    ],
  },
  {
    id: "pharm-gen-005",
    fact: "Enzyme induction (e.g., rifampin inducing CYP3A4) increases drug metabolism, reducing plasma concentrations of co-administered drugs. Enzyme inhibition (e.g., cimetidine inhibiting CYP450) decreases metabolism, increasing drug levels and potential toxicity.",
    specialty: "Pharmacology",
    topic: "Drug Interactions",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Enzyme Induction and Inhibition", "https://www.ncbi.nlm.nih.gov/books/NBK553164/", "statpearls", 1),
      ref("FDA - Drug Interactions", "https://www.fda.gov/drugs/drug-interactions-labeling", "fda", 2),
    ],
  },
  {
    id: "pharm-gen-006",
    fact: "Drugs with zero-order kinetics (saturable metabolism) include aspirin (in high doses), phenytoin, ethanol, and theophylline. The elimination rate is constant regardless of plasma concentration.",
    specialty: "Pharmacology",
    topic: "Pharmacokinetics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Zero-Order Kinetics", "https://www.ncbi.nlm.nih.gov/books/NBK549887/", "statpearls", 1),
      ref("PubMed - Nonlinear Pharmacokinetics", "https://pubmed.ncbi.nlm.nih.gov/33756330/", "pubmed", 1, "33756330"),
    ],
  },

  // ===== AUTONOMIC NERVOUS SYSTEM =====
  {
    id: "pharm-ans-001",
    fact: "Atropine is a competitive antagonist of muscarinic acetylcholine receptors. It blocks the effects of excess acetylcholine, used to treat bradycardia, organophosphate poisoning, and as a preanesthetic to reduce secretions.",
    specialty: "Pharmacology",
    topic: "Autonomic Nervous System",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Atropine", "https://www.ncbi.nlm.nih.gov/books/NBK470551/", "statpearls", 1),
      ref("WHO Model List of Essential Medicines", "https://www.who.int/groups/expert-committee-on-selection-and-use-of-essential-medicines", "who", 1),
    ],
  },
  {
    id: "pharm-ans-002",
    fact: "Prazosin is a selective alpha-1 adrenergic receptor antagonist used for hypertension and benign prostatic hyperplasia. First-dose phenomenon (orthostatic hypotension) is a notable adverse effect.",
    specialty: "Pharmacology",
    topic: "ANS - Alpha Blockers",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Prazosin", "https://www.ncbi.nlm.nih.gov/books/NBK556102/", "statpearls", 1),
      ref("PubMed - Alpha-blockers review", "https://pubmed.ncbi.nlm.nih.gov/30672813/", "pubmed", 1, "30672813"),
    ],
  },
  {
    id: "pharm-ans-003",
    fact: "Propranolol is a non-selective beta-blocker (beta-1 and beta-2). It is contraindicated in asthma due to beta-2 blockade causing bronchoconstriction, and in diabetes due to masking of hypoglycemia-induced tachycardia.",
    specialty: "Pharmacology",
    topic: "ANS - Beta Blockers",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Propranolol", "https://www.ncbi.nlm.nih.gov/books/NBK557801/", "statpearls", 1),
      ref("PubMed - Beta-blocker contraindications", "https://pubmed.ncbi.nlm.nih.gov/30814275/", "pubmed", 1, "30814275"),
    ],
  },
  {
    id: "pharm-ans-004",
    fact: "Neostigmine is a reversible acetylcholinesterase inhibitor used for myasthenia gravis and reversal of non-depolarizing neuromuscular blockade. It increases acetylcholine availability at the neuromuscular junction.",
    specialty: "Pharmacology",
    topic: "Parasympathomimetics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Neostigmine", "https://www.ncbi.nlm.nih.gov/books/NBK470596/", "statpearls", 1),
      ref("PubMed - Acetylcholinesterase inhibitors", "https://pubmed.ncbi.nlm.nih.gov/34322130/", "pubmed", 1, "34322130"),
    ],
  },
  {
    id: "pharm-ans-005",
    fact: "Succinylcholine is a depolarizing neuromuscular blocker that causes initial muscle fasciculations followed by paralysis. It is metabolized by plasma pseudocholinesterase. Prolonged apnea can occur in patients with pseudocholinesterase deficiency.",
    specialty: "Pharmacology",
    topic: "Neuromuscular Blockers",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Succinylcholine", "https://www.ncbi.nlm.nih.gov/books/NBK534223/", "statpearls", 1),
      ref("PubMed - Pseudocholinesterase deficiency", "https://pubmed.ncbi.nlm.nih.gov/30701146/", "pubmed", 1, "30701146"),
    ],
  },
  {
    id: "pharm-ans-006",
    fact: "Salbutamol (albuterol) is a selective beta-2 agonist used as a bronchodilator in asthma and COPD. Common adverse effects include tremor, tachycardia, and hypokalemia from beta-2 mediated potassium shift into cells.",
    specialty: "Pharmacology",
    topic: "Beta-2 Agonists",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Albuterol", "https://www.ncbi.nlm.nih.gov/books/NBK556074/", "statpearls", 1),
      ref("PubMed - Beta-2 agonists in asthma", "https://pubmed.ncbi.nlm.nih.gov/32311827/", "pubmed", 1, "32311827"),
    ],
  },
  {
    id: "pharm-ans-007",
    fact: "Pilocarpine is a direct-acting muscarinic agonist used topically for glaucoma (constricts pupil and increases aqueous humor outflow). Systemic effects include bradycardia, sweating, and salivation.",
    specialty: "Pharmacology",
    topic: "Parasympathomimetics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Pilocarpine", "https://www.ncbi.nlm.nih.gov/books/NBK556128/", "statpearls", 1),
      ref("PubMed - Glaucoma pharmacotherapy", "https://pubmed.ncbi.nlm.nih.gov/31920475/", "pubmed", 1, "31920475"),
    ],
  },

  // ===== CARDIOVASCULAR =====
  {
    id: "pharm-cvs-001",
    fact: "ACE inhibitors (e.g., captopril, enalapril) block the conversion of angiotensin I to angiotensin II, reducing vasoconstriction and aldosterone secretion. Adverse effects include dry cough (due to bradykinin accumulation) and angioedema.",
    specialty: "Pharmacology",
    topic: "Antihypertensives - ACE Inhibitors",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - ACE Inhibitors", "https://www.ncbi.nlm.nih.gov/books/NBK557523/", "statpearls", 1),
      ref("PubMed - ACE inhibitor adverse effects", "https://pubmed.ncbi.nlm.nih.gov/31424792/", "pubmed", 1, "31424792"),
    ],
  },
  {
    id: "pharm-cvs-002",
    fact: "Amlodipine is a dihydropyridine calcium channel blocker that primarily acts on vascular smooth muscle, causing vasodilation. It has minimal cardiac depressant effect compared to verapamil. Used for hypertension and angina.",
    specialty: "Pharmacology",
    topic: "Calcium Channel Blockers",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Amlodipine", "https://www.ncbi.nlm.nih.gov/books/NBK539772/", "statpearls", 1),
      ref("PubMed - CCBs in hypertension", "https://pubmed.ncbi.nlm.nih.gov/33001338/", "pubmed", 1, "33001338"),
    ],
  },
  {
    id: "pharm-cvs-003",
    fact: "Verapamil is a non-dihydropyridine calcium channel blocker that acts on cardiac muscle and SA/AV nodes. It is used for supraventricular tachycardia, angina, and hypertension. Causes constipation as a common side effect.",
    specialty: "Pharmacology",
    topic: "Calcium Channel Blockers",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Verapamil", "https://www.ncbi.nlm.nih.gov/books/NBK537163/", "statpearls", 1),
      ref("PubMed - Verapamil clinical use", "https://pubmed.ncbi.nlm.nih.gov/30658188/", "pubmed", 1, "30658188"),
    ],
  },
  {
    id: "pharm-cvs-004",
    fact: "Digoxin inhibits Na+/K+ ATPase, increasing intracellular sodium, which reduces calcium extrusion via Na+/Ca2+ exchanger, leading to increased cardiac contractility (positive inotrope). Used in heart failure with reduced ejection fraction and atrial fibrillation. Narrow therapeutic index: 0.5-2.0 ng/mL.",
    specialty: "Pharmacology",
    topic: "Cardiac Glycosides",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Digoxin", "https://www.ncbi.nlm.nih.gov/books/NBK556005/", "statpearls", 1),
      ref("PubMed - Digoxin in heart failure", "https://pubmed.ncbi.nlm.nih.gov/32349924/", "pubmed", 1, "32349924"),
    ],
  },
  {
    id: "pharm-cvs-005",
    fact: "Lidocaine is a class IB antiarrhythmic that blocks sodium channels with rapid kinetics. It is used for ventricular arrhythmias, especially post-MI. It undergoes extensive first-pass metabolism and is given intravenously.",
    specialty: "Pharmacology",
    topic: "Antiarrhythmics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Lidocaine", "https://www.ncbi.nlm.nih.gov/books/NBK551679/", "statpearls", 1),
      ref("PubMed - Lidocaine antiarrhythmic", "https://pubmed.ncbi.nlm.nih.gov/31823253/", "pubmed", 1, "31823253"),
    ],
  },
  {
    id: "pharm-cvs-006",
    fact: "Amiodarone is a class III antiarrhythmic that prolongs the action potential duration by blocking potassium channels. It has multiple effects (also class I, II, IV) and can cause pulmonary fibrosis, thyroid dysfunction, liver toxicity, corneal deposits, and blue-gray skin discoloration.",
    specialty: "Pharmacology",
    topic: "Antiarrhythmics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Amiodarone", "https://www.ncbi.nlm.nih.gov/books/NBK482154/", "statpearls", 1),
      ref("PubMed - Amiodarone toxicity", "https://pubmed.ncbi.nlm.nih.gov/32445564/", "pubmed", 1, "32445564"),
    ],
  },
  {
    id: "pharm-cvs-007",
    fact: "Atorvastatin is an HMG-CoA reductase inhibitor that lowers LDL cholesterol by inhibiting the rate-limiting step in cholesterol synthesis. Adverse effects include myopathy, hepatotoxicity, and increased risk of type 2 diabetes.",
    specialty: "Pharmacology",
    topic: "Lipid-Lowering Drugs",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Atorvastatin", "https://www.ncbi.nlm.nih.gov/books/NBK545226/", "statpearls", 1),
      ref("PubMed - Statin therapy guidelines", "https://pubmed.ncbi.nlm.nih.gov/33064565/", "pubmed", 1, "33064565"),
    ],
  },
  {
    id: "pharm-cvs-008",
    fact: "Sodium nitroprusside is a direct vasodilator (both arterial and venous) that releases nitric oxide. It is used in hypertensive emergencies. Prolonged use can cause cyanide toxicity, especially in renal failure.",
    specialty: "Pharmacology",
    topic: "Antihypertensives - Vasodilators",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Nitroprusside", "https://www.ncbi.nlm.nih.gov/books/NBK557700/", "statpearls", 1),
      ref("PubMed - Hypertensive emergencies", "https://pubmed.ncbi.nlm.nih.gov/31990389/", "pubmed", 1, "31990389"),
    ],
  },

  // ===== CNS PHARMACOLOGY =====
  {
    id: "pharm-cns-001",
    fact: "Phenytoin is a class IB antiarrhythmic and antiepileptic that blocks voltage-gated sodium channels in a use-dependent manner. It exhibits zero-order kinetics, making dose adjustments critical. Gingival hyperplasia, hirsutism, and nystagmus are common adverse effects.",
    specialty: "Pharmacology",
    topic: "Antiepileptics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Phenytoin", "https://www.ncbi.nlm.nih.gov/books/NBK545261/", "statpearls", 1),
      ref("PubMed - Phenytoin pharmacokinetics", "https://pubmed.ncbi.nlm.nih.gov/31535845/", "pubmed", 1, "31535845"),
    ],
  },
  {
    id: "pharm-cns-002",
    fact: "Valproic acid (sodium valproate) increases GABA levels by inhibiting GABA transaminase and blocking voltage-gated sodium channels. It is a broad-spectrum antiepileptic effective for absence, tonic-clonic, and myoclonic seizures. Hepatotoxicity and neural tube defects (teratogenic) are major concerns.",
    specialty: "Pharmacology",
    topic: "Antiepileptics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Valproic Acid", "https://www.ncbi.nlm.nih.gov/books/NBK534849/", "statpearls", 1),
      ref("PubMed - Valproate teratogenicity", "https://pubmed.ncbi.nlm.nih.gov/30749565/", "pubmed", 1, "30749565"),
    ],
  },
  {
    id: "pharm-cns-003",
    fact: "Fluoxetine is a selective serotonin reuptake inhibitor (SSRI) used for major depressive disorder, OCD, bulimia nervosa, and panic disorder. It has a long half-life (4-6 days, including active metabolite norfluoxetine). Side effects include sexual dysfunction, GI upset, and serotonin syndrome when combined with MAOIs.",
    specialty: "Pharmacology",
    topic: "Antidepressants - SSRIs",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Fluoxetine", "https://www.ncbi.nlm.nih.gov/books/NBK553154/", "statpearls", 1),
      ref("PubMed - SSRI clinical guidelines", "https://pubmed.ncbi.nlm.nih.gov/32192101/", "pubmed", 1, "32192101"),
    ],
  },
  {
    id: "pharm-cns-004",
    fact: "Amitriptyline is a tricyclic antidepressant (TCA) that blocks reuptake of serotonin and norepinephrine. It also has anticholinergic and sedative properties. Used for depression, neuropathic pain, migraine prophylaxis. Overdose causes QT prolongation and cardiotoxicity.",
    specialty: "Pharmacology",
    topic: "Antidepressants - TCAs",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Amitriptyline", "https://www.ncbi.nlm.nih.gov/books/NBK537225/", "statpearls", 1),
      ref("PubMed - TCA overdose management", "https://pubmed.ncbi.nlm.nih.gov/30899435/", "pubmed", 1, "30899435"),
    ],
  },
  {
    id: "pharm-cns-005",
    fact: "Haloperidol is a typical antipsychotic (butyrophenone) that blocks dopamine D2 receptors. Used for schizophrenia, acute psychosis, and Tourette syndrome. Extrapyramidal side effects (dystonia, parkinsonism, akathisia) are common. Neuroleptic malignant syndrome is a rare but life-threatening adverse effect.",
    specialty: "Pharmacology",
    topic: "Antipsychotics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Haloperidol", "https://www.ncbi.nlm.nih.gov/books/NBK534892/", "statpearls", 1),
      ref("PubMed - Antipsychotic adverse effects", "https://pubmed.ncbi.nlm.nih.gov/31587375/", "pubmed", 1, "31587375"),
    ],
  },
  {
    id: "pharm-cns-006",
    fact: "Clozapine is an atypical antipsychotic that blocks serotonin 5-HT2A and dopamine D4 receptors more than D2. It is used for treatment-resistant schizophrenia. Agranulocytosis is a serious adverse effect requiring regular WBC monitoring. It has minimal extrapyramidal side effects.",
    specialty: "Pharmacology",
    topic: "Antipsychotics - Atypical",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Clozapine", "https://www.ncbi.nlm.nih.gov/books/NBK535399/", "statpearls", 1),
      ref("PubMed - Clozapine monitoring guidelines", "https://pubmed.ncbi.nlm.nih.gov/33523782/", "pubmed", 1, "33523782"),
    ],
  },
  {
    id: "pharm-cns-007",
    fact: "Diazepam is a benzodiazepine that enhances GABA-A receptor chloride channel opening. It has anxiolytic, sedative-hypnotic, anticonvulsant, and muscle relaxant properties. Flumazenil is the competitive antagonist used for overdose reversal.",
    specialty: "Pharmacology",
    topic: "Benzodiazepines",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Diazepam", "https://www.ncbi.nlm.nih.gov/books/NBK537022/", "statpearls", 1),
      ref("WHO Model Prescribing Information", "https://www.who.int/medicines/publications/essentialmedicines/en/", "who", 1),
    ],
  },
  {
    id: "pharm-cns-008",
    fact: "Levodopa combined with carbidopa is the most effective treatment for Parkinson's disease. Carbidopa inhibits peripheral dopa decarboxylase, preventing peripheral conversion of levodopa to dopamine and reducing side effects. Long-term use leads to motor fluctuations (on-off phenomenon) and dyskinesias.",
    specialty: "Pharmacology",
    topic: "Antiparkinsonian Drugs",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Carbidopa/Levodopa", "https://www.ncbi.nlm.nih.gov/books/NBK553150/", "statpearls", 1),
      ref("PubMed - Parkinson's pharmacotherapy", "https://pubmed.ncbi.nlm.nih.gov/32242678/", "pubmed", 1, "32242678"),
    ],
  },
  {
    id: "pharm-cns-009",
    fact: "Morphine is a mu-opioid receptor agonist used for moderate to severe pain. It causes respiratory depression (dose-limiting toxicity), constipation, nausea, pruritus, and dependence. Naloxone is a competitive antagonist that reverses opioid effects.",
    specialty: "Pharmacology",
    topic: "Opioid Analgesics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Morphine", "https://www.ncbi.nlm.nih.gov/books/NBK547733/", "statpearls", 1),
      ref("PubMed - Opioid pharmacology", "https://pubmed.ncbi.nlm.nih.gov/31818862/", "pubmed", 1, "31818862"),
    ],
  },

  // ===== ENDOCRINE PHARMACOLOGY =====
  {
    id: "pharm-end-001",
    fact: "Metformin is a biguanide that reduces hepatic gluconeogenesis, increases peripheral glucose uptake, and improves insulin sensitivity. It is first-line therapy for type 2 diabetes mellitus. Lactic acidosis is a rare but serious adverse effect, contraindicated in renal impairment (eGFR <30).",
    specialty: "Pharmacology",
    topic: "Antidiabetics - Biguanides",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Metformin", "https://www.ncbi.nlm.nih.gov/books/NBK542274/", "statpearls", 1),
      ref("PubMed - Metformin clinical guidelines", "https://pubmed.ncbi.nlm.nih.gov/33186748/", "pubmed", 1, "33186748"),
    ],
  },
  {
    id: "pharm-end-002",
    fact: "Insulin glargine is a long-acting recombinant insulin analogue with a duration of 20-24 hours. It forms microprecipitates at the injection site that slowly release insulin, providing a peakless basal insulin level. Used for basal insulin coverage in type 1 and type 2 diabetes.",
    specialty: "Pharmacology",
    topic: "Insulin Therapy",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Insulin Glargine", "https://www.ncbi.nlm.nih.gov/books/NKB557773/", "statpearls", 1),
      ref("PubMed - Insulin analogues review", "https://pubmed.ncbi.nlm.nih.gov/32809672/", "pubmed", 1, "32809672"),
    ],
  },
  {
    id: "pharm-end-003",
    fact: "Propylthiouracil (PTU) inhibits thyroid peroxidase, blocking thyroid hormone synthesis. It also inhibits peripheral conversion of T4 to T3. Used for hyperthyroidism and thyroid storm. Hepatotoxicity is a serious adverse effect, more common with PTU than methimazole.",
    specialty: "Pharmacology",
    topic: "Antithyroid Drugs",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Propylthiouracil", "https://www.ncbi.nlm.nih.gov/books/NBK549864/", "statpearls", 1),
      ref("PubMed - Antithyroid drug safety", "https://pubmed.ncbi.nlm.nih.gov/30827489/", "pubmed", 1, "30827489"),
    ],
  },
  {
    id: "pharm-end-004",
    fact: "Prednisolone is a glucocorticoid with potent anti-inflammatory and immunosuppressant effects. It acts via intracellular glucocorticoid receptors, modulating gene transcription. Long-term use causes Cushing's syndrome, osteoporosis, hyperglycemia, immunosuppression, and adrenal suppression (withdrawal can cause adrenal crisis).",
    specialty: "Pharmacology",
    topic: "Corticosteroids",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Prednisolone", "https://www.ncbi.nlm.nih.gov/books/NBK545276/", "statpearls", 1),
      ref("PubMed - Glucocorticoid therapy guidelines", "https://pubmed.ncbi.nlm.nih.gov/32208287/", "pubmed", 1, "32208287"),
    ],
  },

  // ===== CHEMOTHERAPY / ANTIMICROBIALS =====
  {
    id: "pharm-chem-001",
    fact: "Penicillin G is a bactericidal beta-lactam antibiotic that inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins (PBPs). It is effective against Gram-positive cocci, spirochetes, and some Gram-negative cocci. Resistance is primarily via beta-lactamase production.",
    specialty: "Pharmacology",
    topic: "Antibiotics - Penicillins",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Penicillin", "https://www.ncbi.nlm.nih.gov/books/NBK542294/", "statpearls", 1),
      ref("PubMed - Beta-lactam antibiotics", "https://pubmed.ncbi.nlm.nih.gov/31732174/", "pubmed", 1, "31732174"),
    ],
  },
  {
    id: "pharm-chem-002",
    fact: "Ceftriaxone is a third-generation cephalosporin with enhanced activity against Gram-negative bacteria including Enterobacteriaceae and Neisseria gonorrhoeae. It crosses the blood-brain barrier and is used for meningitis. It is contraindicated in neonates with hyperbilirubinemia (displaces bilirubin from albumin).",
    specialty: "Pharmacology",
    topic: "Antibiotics - Cephalosporins",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Ceftriaxone", "https://www.ncbi.nlm.nih.gov/books/NBK557656/", "statpearls", 1),
      ref("PubMed - Cephalosporin classification", "https://pubmed.ncbi.nlm.nih.gov/30969654/", "pubmed", 1, "30969654"),
    ],
  },
  {
    id: "pharm-chem-003",
    fact: "Azithromycin is a macrolide antibiotic that binds to the 50S ribosomal subunit, inhibiting bacterial protein synthesis. It has good tissue penetration and a long half-life (~68 hours). Used for respiratory infections, atypical pneumonias, and sexually transmitted infections. QT prolongation is a concern.",
    specialty: "Pharmacology",
    topic: "Antibiotics - Macrolides",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Azithromycin", "https://www.ncbi.nlm.nih.gov/books/NBK557766/", "statpearls", 1),
      ref("PubMed - Macrolide antibiotics review", "https://pubmed.ncbi.nlm.nih.gov/33079460/", "pubmed", 1, "33079460"),
    ],
  },
  {
    id: "pharm-chem-004",
    fact: "Gentamicin is an aminoglycoside that binds to the 30S ribosomal subunit, causing misreading of mRNA and bacterial protein synthesis inhibition. It is bactericidal against Gram-negative aerobes. Nephrotoxicity and ototoxicity (both vestibular and cochlear) are dose-limiting adverse effects.",
    specialty: "Pharmacology",
    topic: "Antibiotics - Aminoglycosides",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Gentamicin", "https://www.ncbi.nlm.nih.gov/books/NBK534324/", "statpearls", 1),
      ref("PubMed - Aminoglycoside toxicity monitoring", "https://pubmed.ncbi.nlm.nih.gov/31442514/", "pubmed", 1, "31442514"),
    ],
  },
  {
    id: "pharm-chem-005",
    fact: "Ciprofloxacin is a fluoroquinolone that inhibits bacterial DNA gyrase (topoisomerase II) and topoisomerase IV, preventing DNA replication. It is active against Gram-negative bacteria including Pseudomonas aeruginosa. Side effects include tendonitis/tendon rupture, QT prolongation, and CNS effects. Contraindicated in children (<18 years) due to cartilage damage risk.",
    specialty: "Pharmacology",
    topic: "Antibiotics - Fluoroquinolones",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Ciprofloxacin", "https://www.ncbi.nlm.nih.gov/books/NBK535454/", "statpearls", 1),
      ref("FDA - Fluoroquinolone safety labeling", "https://www.fda.gov/drugs/drug-safety-and-availability/fda-drug-safety-communication-fda-updates-warnings-oral-and-injectable-fluoroquinolone-antibiotics", "fda", 2),
    ],
  },
  {
    id: "pharm-chem-006",
    fact: "Metronidazole is a nitroimidazole that becomes reduced intracellularly in anaerobic organisms, damaging DNA and inhibiting nucleic acid synthesis. It is active against anaerobic bacteria and protozoa (Giardia, Trichomonas, Entamoeba). Disulfiram-like reaction occurs with alcohol consumption.",
    specialty: "Pharmacology",
    topic: "Antibiotics - Metronidazole",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Metronidazole", "https://www.ncbi.nlm.nih.gov/books/NBK539728/", "statpearls", 1),
      ref("PubMed - Metronidazole mechanism", "https://pubmed.ncbi.nlm.nih.gov/32015747/", "pubmed", 1, "32015747"),
    ],
  },
  {
    id: "pharm-chem-007",
    fact: "Isoniazid (INH) inhibits mycolic acid synthesis in Mycobacterium tuberculosis. It is a first-line antitubercular drug. Peripheral neuropathy (due to pyridoxine depletion) and hepatotoxicity are major adverse effects. Acetylator phenotype (slow vs. fast) affects its metabolism.",
    specialty: "Pharmacology",
    topic: "Antitubercular Drugs",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Isoniazid", "https://www.ncbi.nlm.nih.gov/books/NBK544359/", "statpearls", 1),
      ref("PubMed - TB treatment guidelines", "https://pubmed.ncbi.nlm.nih.gov/33999589/", "pubmed", 1, "33999589"),
    ],
  },
  {
    id: "pharm-chem-008",
    fact: "Rifampicin is a bactericidal antitubercular drug that inhibits bacterial DNA-dependent RNA polymerase. It is a potent CYP450 inducer, reducing levels of oral contraceptives, warfarin, and many other drugs. It causes orange-red discoloration of bodily fluids.",
    specialty: "Pharmacology",
    topic: "Antitubercular Drugs",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Rifampicin", "https://www.ncbi.nlm.nih.gov/books/NBK557610/", "statpearls", 1),
      ref("PubMed - Rifampicin drug interactions", "https://pubmed.ncbi.nlm.nih.gov/31973743/", "pubmed", 1, "31973743"),
    ],
  },
  {
    id: "pharm-chem-009",
    fact: "Chloroquine is a 4-aminoquinoline antimalarial that inhibits heme polymerase in the parasite, leading to toxic accumulation of heme. It is used for P. vivax, P. ovale, and P. malariae, but resistance is widespread in P. falciparum. It can cause retinopathy with long-term use.",
    specialty: "Pharmacology",
    topic: "Antimalarials",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Chloroquine", "https://www.ncbi.nlm.nih.gov/books/NBK551652/", "statpearls", 1),
      ref("WHO Guidelines for Malaria", "https://www.who.int/publications/i/item/guidelines-for-malaria", "who", 1),
    ],
  },
  {
    id: "pharm-chem-010",
    fact: "Methotrexate is a folate analogue that inhibits dihydrofolate reductase (DHFR), interfering with DNA synthesis. It is used for cancer chemotherapy, rheumatoid arthritis, and psoriasis. Folinic acid (leucovorin) rescue is administered to reduce toxicity to normal cells.",
    specialty: "Pharmacology",
    topic: "Anticancer - Antimetabolites",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Methotrexate", "https://www.ncbi.nlm.nih.gov/books/NBK545267/", "statpearls", 1),
      ref("PubMed - Methotrexate therapy", "https://pubmed.ncbi.nlm.nih.gov/31424899/", "pubmed", 1, "31424899"),
    ],
  },
  {
    id: "pharm-chem-011",
    fact: "Doxorubicin is an anthracycline antibiotic that intercalates DNA and inhibits topoisomerase II, blocking DNA replication. Its dose-limiting toxicity is cardiotoxicity (dilated cardiomyopathy). Dexrazoxane is used for cardioprotection.",
    specialty: "Pharmacology",
    topic: "Anticancer - Anthracyclines",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Doxorubicin", "https://www.ncbi.nlm.nih.gov/books/NBK545228/", "statpearls", 1),
      ref("PubMed - Anthracycline cardiotoxicity", "https://pubmed.ncbi.nlm.nih.gov/32397005/", "pubmed", 1, "32397005"),
    ],
  },

  // ===== DIURETICS =====
  {
    id: "pharm-renal-001",
    fact: "Furosemide is a loop diuretic that inhibits the Na+/K+/2Cl- cotransporter in the thick ascending limb of the loop of Henle. It is a high-ceiling diuretic used for pulmonary edema, heart failure, and hypertension. Adverse effects include hypokalemia, hypocalcemia, ototoxicity, and hyperuricemia.",
    specialty: "Pharmacology",
    topic: "Diuretics - Loop",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Furosemide", "https://www.ncbi.nlm.nih.gov/books/NBK547707/", "statpearls", 1),
      ref("PubMed - Loop diuretic use in heart failure", "https://pubmed.ncbi.nlm.nih.gov/30869711/", "pubmed", 1, "30869711"),
    ],
  },
  {
    id: "pharm-renal-002",
    fact: "Spironolactone is a potassium-sparing diuretic that competitively antagonizes aldosterone at the distal convoluted tubule and collecting duct. It is used for heart failure (aldosterone antagonist in HFrEF), primary hyperaldosteronism, and hirsutism. Hyperkalemia and gynecomastia are notable adverse effects.",
    specialty: "Pharmacology",
    topic: "Diuretics - K+ Sparing",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Spironolactone", "https://www.ncbi.nlm.nih.gov/books/NBK500008/", "statpearls", 1),
      ref("PubMed - Aldosterone antagonists in HF", "https://pubmed.ncbi.nlm.nih.gov/32234120/", "pubmed", 1, "32234120"),
    ],
  },
  {
    id: "pharm-renal-003",
    fact: "Acetazolamide is a carbonic anhydrase inhibitor that acts in the proximal convoluted tubule, reducing bicarbonate reabsorption. It causes metabolic acidosis. Used for glaucoma, altitude sickness, and as a urinary alkalinizer. It is a sulfonamide derivative.",
    specialty: "Pharmacology",
    topic: "Diuretics - CA Inhibitors",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Acetazolamide", "https://www.ncbi.nlm.nih.gov/books/NBK535428/", "statpearls", 1),
      ref("PubMed - Carbonic anhydrase inhibitors", "https://pubmed.ncbi.nlm.nih.gov/30737187/", "pubmed", 1, "30737187"),
    ],
  },

  // ===== RESPIRATORY =====
  {
    id: "pharm-resp-001",
    fact: "Ipratropium bromide is an anticholinergic bronchodilator (muscarinic antagonist) used for COPD and asthma. It is a quaternary ammonium compound with minimal systemic absorption, thus has fewer systemic side effects than atropine. Given via inhalation.",
    specialty: "Pharmacology",
    topic: "Respiratory - Anticholinergics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Ipratropium", "https://www.ncbi.nlm.nih.gov/books/NBK545226/", "statpearls", 1),
      ref("PubMed - Anticholinergics in COPD", "https://pubmed.ncbi.nlm.nih.gov/30685466/", "pubmed", 1, "30685466"),
    ],
  },
  {
    id: "pharm-resp-002",
    fact: "Theophylline is a methylxanthine that causes bronchodilation via non-selective phosphodiesterase inhibition (increasing cAMP) and adenosine receptor antagonism. It has a narrow therapeutic index (10-20 mcg/mL). Toxicity causes tachycardia, seizures, and vomiting.",
    specialty: "Pharmacology",
    topic: "Respiratory - Methylxanthines",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Theophylline", "https://www.ncbi.nlm.nih.gov/books/NBK538211/", "statpearls", 1),
      ref("PubMed - Theophylline in asthma", "https://pubmed.ncbi.nlm.nih.gov/32246871/", "pubmed", 1, "32246871"),
    ],
  },
  {
    id: "pharm-resp-003",
    fact: "Inhaled corticosteroids (e.g., beclomethasone, fluticasone) are the cornerstone of controller therapy in persistent asthma. They reduce airway inflammation through glucocorticoid receptor activation. Oropharyngeal candidiasis and dysphonia are local side effects.",
    specialty: "Pharmacology",
    topic: "Respiratory - Corticosteroids",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Inhaled Corticosteroids", "https://www.ncbi.nlm.nih.gov/books/NBK542221/", "statpearls", 1),
      ref("GINA Guidelines for Asthma", "https://ginasthma.org/gina-reports/", "guideline", 1),
    ],
  },

  // ===== NSAIDs & ANALGESICS =====
  {
    id: "pharm-nsaid-001",
    fact: "Aspirin (acetylsalicylic acid) irreversibly acetylates cyclooxygenase (COX-1 and COX-2), inhibiting prostaglandin and thromboxane synthesis. Low-dose aspirin (75-150 mg) selectively inhibits platelet COX-1, providing antiplatelet effect. It is used for primary and secondary prevention of cardiovascular events.",
    specialty: "Pharmacology",
    topic: "NSAIDs - Aspirin",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Aspirin", "https://www.ncbi.nlm.nih.gov/books/NBK545203/", "statpearls", 1),
      ref("PubMed - Aspirin for CVD prevention", "https://pubmed.ncbi.nlm.nih.gov/33066010/", "pubmed", 1, "33066010"),
    ],
  },
  {
    id: "pharm-nsaid-002",
    fact: "Paracetamol (acetaminophen) is an analgesic and antipyretic with weak anti-inflammatory activity. Its mechanism involves inhibition of COX-2 in the CNS and interaction with the serotonergic system. Overdose causes hepatotoxicity due to accumulation of the toxic metabolite NAPQI, which depletes glutathione. N-acetylcysteine is the antidote.",
    specialty: "Pharmacology",
    topic: "Paracetamol",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Acetaminophen", "https://www.ncbi.nlm.nih.gov/books/NBK556048/", "statpearls", 1),
      ref("PubMed - Paracetamol toxicity mechanism", "https://pubmed.ncbi.nlm.nih.gov/32399684/", "pubmed", 1, "32399684"),
    ],
  },
  {
    id: "pharm-nsaid-003",
    fact: "Celecoxib is a selective COX-2 inhibitor NSAID that provides anti-inflammatory and analgesic effects with reduced GI side effects compared to non-selective NSAIDs. However, it increases risk of cardiovascular events (MI, stroke) and is contraindicated in patients with established CVD or post-CABG surgery.",
    specialty: "Pharmacology",
    topic: "NSAIDs - COX-2 Inhibitors",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Celecoxib", "https://www.ncbi.nlm.nih.gov/books/NBK535449/", "statpearls", 1),
      ref("FDA - COX-2 inhibitor safety", "https://www.fda.gov/drugs/postmarket-drug-safety-information-patients-and-providers/cox-2-selective-includes-bev-other-non-steroidal-anti-inflammatory-drugs-nsaids", "fda", 2),
    ],
  },

  // ===== HEMATOLOGY =====
  {
    id: "pharm-heme-001",
    fact: "Warfarin inhibits vitamin K epoxide reductase (VKORC1), preventing the regeneration of reduced vitamin K required for gamma-carboxylation of clotting factors II, VII, IX, X and proteins C and S. Its effect is monitored by INR (therapeutic range 2-3 for most indications). Vitamin K is the antidote for reversal.",
    specialty: "Pharmacology",
    topic: "Anticoagulants - Warfarin",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Warfarin", "https://www.ncbi.nlm.nih.gov/books/NBK547709/", "statpearls", 1),
      ref("PubMed - Warfarin pharmacology", "https://pubmed.ncbi.nlm.nih.gov/30882955/", "pubmed", 1, "30882955"),
    ],
  },
  {
    id: "pharm-heme-002",
    fact: "Heparin potentiates antithrombin III, inactivating thrombin (factor IIa) and factor Xa. Unfractionated heparin is monitored by aPTT (1.5-2.5x control). Protamine sulfate is the reversal agent. Heparin-induced thrombocytopenia (HIT) is an immune-mediated adverse effect.",
    specialty: "Pharmacology",
    topic: "Anticoagulants - Heparin",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Heparin", "https://www.ncbi.nlm.nih.gov/books/NBK538524/", "statpearls", 1),
      ref("PubMed - HIT diagnosis and management", "https://pubmed.ncbi.nlm.nih.gov/30729712/", "pubmed", 1, "30729712"),
    ],
  },
  {
    id: "pharm-heme-003",
    fact: "Clopidogrel is a thienopyridine P2Y12 receptor antagonist that irreversibly inhibits ADP-induced platelet aggregation. It is a prodrug that requires CYP2C19 activation. Used in acute coronary syndrome, post-stent, and in combination with aspirin (DAPT).",
    specialty: "Pharmacology",
    topic: "Antiplatelets",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Clopidogrel", "https://www.ncbi.nlm.nih.gov/books/NBK545253/", "statpearls", 1),
      ref("PubMed - Antiplatelet therapy guidelines", "https://pubmed.ncbi.nlm.nih.gov/33047768/", "pubmed", 1, "33047768"),
    ],
  },

  // ===== GI PHARMACOLOGY =====
  {
    id: "pharm-gi-001",
    fact: "Omeprazole is a proton pump inhibitor (PPI) that irreversibly binds to H+/K+ ATPase in gastric parietal cells, suppressing gastric acid secretion. It is a prodrug activated in the acidic environment of the parietal cell canaliculus. Used for GERD, PUD, Zollinger-Ellison syndrome, and H. pylori eradication.",
    specialty: "Pharmacology",
    topic: "GI - Proton Pump Inhibitors",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Omeprazole", "https://www.ncbi.nlm.nih.gov/books/NBK539785/", "statpearls", 1),
      ref("PubMed - PPI therapy guidelines", "https://pubmed.ncbi.nlm.nih.gov/31992944/", "pubmed", 1, "31992944"),
    ],
  },
  {
    id: "pharm-gi-002",
    fact: "Ondansetron is a selective 5-HT3 receptor antagonist used for prevention of nausea and vomiting, including chemotherapy-induced and postoperative nausea. It acts by blocking serotonin receptors in the chemoreceptor trigger zone (CTZ) and GI tract. QT prolongation is a potential adverse effect.",
    specialty: "Pharmacology",
    topic: "GI - Antiemetics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Ondansetron", "https://www.ncbi.nlm.nih.gov/books/NBK553153/", "statpearls", 1),
      ref("PubMed - 5-HT3 antagonists review", "https://pubmed.ncbi.nlm.nih.gov/31904723/", "pubmed", 1, "31904723"),
    ],
  },

  // ===== IMMUNOSUPPRESSANTS =====
  {
    id: "pharm-immu-001",
    fact: "Cyclosporine is a calcineurin inhibitor that blocks IL-2 transcription in T-lymphocytes, preventing T-cell activation and proliferation. It is used for transplant rejection prophylaxis and autoimmune diseases. Nephrotoxicity, hypertension, and gingival hyperplasia are major adverse effects. Monitored by trough levels.",
    specialty: "Pharmacology",
    topic: "Immunosuppressants",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Cyclosporine", "https://www.ncbi.nlm.nih.gov/books/NBK544247/", "statpearls", 1),
      ref("PubMed - Calcineurin inhibitors", "https://pubmed.ncbi.nlm.nih.gov/31641000/", "pubmed", 1, "31641000"),
    ],
  },

  // ===== LOCAL ANESTHETICS =====
  {
    id: "pharm-la-001",
    fact: "Lidocaine is an amide-type local anesthetic that blocks voltage-gated sodium channels, preventing nerve impulse conduction. It has rapid onset and intermediate duration. Bupivacaine is more lipid-soluble with longer duration but greater cardiotoxicity. Ester-type anesthetics (procaine) are metabolized by plasma pseudocholinesterase.",
    specialty: "Pharmacology",
    topic: "Local Anesthetics",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Local Anesthetics", "https://www.ncbi.nlm.nih.gov/books/NBK545198/", "statpearls", 1),
      ref("PubMed - Bupivacaine cardiotoxicity", "https://pubmed.ncbi.nlm.nih.gov/31902258/", "pubmed", 1, "31902258"),
    ],
  },
  {
    id: "pharm-la-002",
    fact: "Bupivacaine is more cardiotoxic than lidocaine due to its higher lipid solubility and greater affinity for cardiac sodium channels. Accidental IV injection can cause refractory ventricular arrhythmias. Lipid emulsion therapy (Intralipid) is used as rescue treatment for bupivacaine cardiotoxicity.",
    specialty: "Pharmacology",
    topic: "Local Anesthetics - Toxicity",
    careerStage: PG_PREP,
    verificationStatus: "unverified",
    foundBy: "finder",
    sources: [
      ref("StatPearls - Local Anesthetic Toxicity", "https://www.ncbi.nlm.nih.gov/books/NBK545202/", "statpearls", 1),
      ref("PubMed - Lipid rescue in LA toxicity", "https://pubmed.ncbi.nlm.nih.gov/33183668/", "pubmed", 1, "33183668"),
    ],
  },
];
