import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  boolean,
  integer,
  real,
  date,
  index,
  jsonb,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { users } from "./users";

/* ═══════════════════════════════════════════
   STUDY_PLANS — Personalised study roadmaps
   Generated by AI or created manually.
   ═══════════════════════════════════════════ */

export const studyPlans = pgTable(
  "study_plans",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    title: varchar("title", { length: 500 }).notNull(),
    description: text("description"),
    examTarget: varchar("exam_target", { length: 100 }), // NEET-PG, USMLE, FMGE, etc.
    startDate: date("start_date").notNull(),
    endDate: date("end_date").notNull(),
    daysPerWeek: integer("days_per_week").default(6).notNull(),
    hoursPerDay: real("hours_per_day").default(4).notNull(),
    aiGenerated: boolean("ai_generated").default(false).notNull(),
    status: varchar("status", { length: 30 }).default("active").notNull(), // active | completed | paused | abandoned
    progressPercent: real("progress_percent").default(0).notNull(),
    metadata: jsonb("metadata"), // custom AI params, revision schedule, etc.
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => ({
    userIdx: index("idx_study_plans_user").on(table.userId),
    statusIdx: index("idx_study_plans_status").on(table.status),
    examIdx: index("idx_study_plans_exam").on(table.examTarget),
  }),
);

/* ═══════════════════════════════════════════
   STUDY_PLAN_ITEMS — Individual milestones
   Each item maps to a subject/topic block.
   ═══════════════════════════════════════════ */

export const studyPlanItems = pgTable(
  "study_plan_items",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    planId: uuid("plan_id")
      .references(() => studyPlans.id, { onDelete: "cascade" })
      .notNull(),
    dayNumber: integer("day_number").notNull(),
    subject: varchar("subject", { length: 255 }).notNull(),
    topicTags: text("topic_tags")
      .array()
      .default(sql`'{}'::text[]`)
      .notNull(),
    estimatedMinutes: integer("estimated_minutes").default(60).notNull(),
    completed: boolean("completed").default(false).notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    planIdx: index("idx_plan_items_plan").on(table.planId),
    dayIdx: index("idx_plan_items_day").on(table.planId, table.dayNumber),
    completedIdx: index("idx_plan_items_completed").on(table.completed),
  }),
);
